In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("E:\datasets\listings 2 reduced.csv")

In [6]:
df.head()

,id,host_id,host_since,host_listings_count,host_identity_verified,calculated_host_listings_count,property_type,room_type,instant_bookable,minimum_nights,...,host_is_superhost,neighbourhood_cleansed,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,description
0,92644,498201,2011-04-10,1.0,t,1,Private room in rental unit,Private room,t,2,...,f,Wandsworth,4.57,4.74,4.86,4.71,4.67,4.53,4.68,<b>The space</b><br />Hi everyone! I have 2 ro...
1,93015,499704,2011-04-11,1.0,t,1,Entire rental unit,Entire home/apt,f,5,...,f,Hammersmith and Fulham,4.82,4.76,4.62,4.85,4.88,4.85,4.74,Gorgeous 2 bed ground floor apartment with per...
2,13913,54730,2009-11-16,3.0,t,2,Private room in rental unit,Private room,f,1,...,f,Islington,4.80,4.72,4.72,4.74,4.82,4.69,4.69,My bright double bedroom with a large window h...
3,15400,60302,2009-12-05,1.0,t,1,Entire rental unit,Entire home/apt,f,7,...,f,Kensington and Chelsea,4.80,4.85,4.88,4.88,4.83,4.93,4.74,Lots of windows and light. St Luke's Gardens ...
4,93734,497514,2011-04-10,1.0,t,1,Private room in condo,Private room,f,4,...,t,Greenwich,4.62,4.70,4.59,4.63,4.81,4.64,4.67,<b>During your stay</b><br />I’m a professiona...

In [11]:
import pandas as pd

# Assuming your dataset is stored in a DataFrame called 'df'

# Step 1: Classify hosts as professional or non-professional
df['host_type'] = df.groupby('host_id')['neighbourhood_cleansed'].transform('nunique')
df['host_type'] = df['host_type'].apply(lambda x: 'professional' if x > 5 else 'non-professional')

# # Step 2: Calculate average price for professional and non-professional hosts
# avg_price_professional = df[df['host_type'] == 'professional']['price'].mean()
# avg_price_non_professional = df[df['host_type'] == 'non-professional']['price'].mean()

# # Step 3: Calculate the average price difference
# price_difference = avg_price_professional - avg_price_non_professional

# print("Average price for professional hosts:", avg_price_professional)
# print("Average price for non-professional hosts:", avg_price_non_professional)
# print("Price difference between professional and non-professional hosts:", price_difference)

0        non-professional
1        non-professional
2        non-professional
3        non-professional
4        non-professional
               ...
87941    non-professional
87942    non-professional
87943    non-professional
87944        professional
87945    non-professional
Name: host_type, Length: 87946, dtype: object

In [1]:
ar = [1,2,3]
for i in ar:
    print(i)

1
2
3